[package]
name = "rustMonkey"
version = "0.1.0"
edition = "2021"
authors = ["Milton"]

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "rustMonkey"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
